server:
  port: 8080

spring:
  datasource:
    ssm:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/awaytest?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root

logging:
  config: classpath:log4j2.xml

